### ISSUE TITLE
Unable to load resnet18 ONNX model

### ISSUE THREAD

**Issue by olivierbichler-cea** [deephealthproject/eddl#133] opened 2020-03-23 16:04 UTC
When I try to load the resnet18v1 ONNX model with the `onnx_import` example, I get a segmentation fault. The resnet18v1 model is taken from the ONNX model zoo at https://github.com/onnx/models/tree/master/vision/classification/resnet.

> Ir_version < 6
> Producer_name: 
> Producer_version: 
> Domain: 
> Model_version: 0
> Input resnetv15_stage1_batchnorm1_fwd Is not avaliable
>  node->op_type   Add is not avaliable
> Input resnetv15_stage1_batchnorm3_fwd Is not avaliable
>  node->op_type   Add is not avaliable
> Input resnetv15_stage2_batchnorm1_fwd Is not avaliable
>  node->op_type   Add is not avaliable
> Input resnetv15_stage2_batchnorm4_fwd Is not avaliable
>  node->op_type   Add is not avaliable
> Input resnetv15_stage3_batchnorm1_fwd Is not avaliable
>  node->op_type   Add is not avaliable
> Input resnetv15_stage3_batchnorm4_fwd Is not avaliable
>  node->op_type   Add is not avaliable
> Input resnetv15_stage4_batchnorm1_fwd Is not avaliable
>  node->op_type   Add is not avaliable
> Input resnetv15_stage4_batchnorm4_fwd Is not avaliable
>  node->op_type   Add is not avaliable
> Segmentation fault (core dumped)

**Comment by RParedesPalacios** [comment] 2020-03-23 18:41
We will see... it is strange since batch norm and Add are implemented- Perhaps the names does not follow the onnx-standard

**Comment by Seraphid** [comment] 2020-03-24 10:38
`Ir_version < 6
Warning: Version is inferior to the one supported. ONNX module will try to load it anyway
Ir_version = 3
Producer_name: 
Producer_version: 
Domain: 
Model_version: 0
Segmentation fault (core dumped)`

Right now it seems that this model uses a previous ONNX version instead of the current avaliable. The errors that are showing up are probably because this difference between versions. I will look further into this issue to see if it can be solved from our side, but the problem comes mainly from the version.

**Comment by Seraphid** [comment] 2020-04-15 11:20
The issue is now fixed. We will upload the onnx code with this issue solved in the next release.

**Closed by Seraphid** 2020-04-15 11:20 UTC
