### ISSUE TITLE
Remove onnx.pb (automatic generation does not work properly)

### ISSUE THREAD

**Issue by salvacarrion** [deephealthproject/eddl#174] opened 2020-06-04 12:10 UTC
Technically, they are generated during building and it works on many computers. 
However, I have noticed that if I remove those files, on GitHub actions we get a "failed building" error.

This is important because those files are dependent on the protobuf version.

**Comment by Seraphid** [comment] 2020-06-05 10:57
The issue was that the source files search was being performed before generating the new files, because they generate in the "make" step, The issue is now fixed.

**Closed by Seraphid** 2020-06-05 10:57 UTC
Labels: bug, priority
